[package]
name = "qiniu"
version = "0.1.0"
authors = ["cuiyunjing"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.19"
data-encoding = "2.3.1"
serde_json = "1.0.60"